apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-consumer
  template:
    metadata:
      labels:
        app: resource-consumer
    spec:
      containers:
      - name: resource-consumer
        image: ghcr.io/stakater/mto/resource-consumer:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
